### ISSUE TITLE
ValueError: 103 is not in list / 50264 not in list

### ISSUE THREAD

**Issue by nelson-liu** [princeton-nlp/LM-BFF#10]
Hi!

I noticed that sometimes, if I run the model on MNLI and set the `max_length` to a value that's insufficiently low (e.g., 128), I'll get the this error:

```
  File "run.py", line 672, in <module>
    main()
  File "run.py", line 469, in main
    if training_args.do_eval
  File "/home/nfliu/git/LM-BFF/src/dataset.py", line 476, in __init__
    verbose=True if _ == 0 else False,
  File "/home/nfliu/git/LM-BFF/src/dataset.py", line 596, in convert_fn
    other_sent_limit=self.args.other_sent_limit,
  File "/home/nfliu/git/LM-BFF/src/dataset.py", line 244, in tokenize_multipart_input
    mask_pos = [input_ids.index(tokenizer.mask_token_id)]
ValueError: 103 is not in list
```

Where you get 103 for BERT models and 50264 for RoBERTa models.

Looking at the code, it seems like the culprit is that when the template produces more input ids than `max_length`, it's truncated down ( https://github.com/princeton-nlp/LM-BFF/blob/main/src/dataset.py#L237 ). However, sometimes, this truncation also removes the MASK token, which leads to the `IndexError` above (seeing this when running on a new dataset that has slightly longer sequence lengths). In this case, would you recommend setting `first_sent_limit` and `other_sent_limit`?

**Comment by gaotianyu1350** [comment]
Hi,

Indeed, since the <mask> token is usually at the end of the sentence (e.g., for SST-2: <sent> It was <mask>), if the max length is small, the input will lose the <mask> token. 

In this case, besides using larger `max_length`, you can also take `first_sent_limit` (which limits the first input sentence's length) and `other_sent_limt` (limits other sentence's length as the name suggests). Also you can try `truncate_head`, which I only tried in GPT-3 style few-shot (because it will prepend lots of examples and the <mask> token is at the end).

**Comment by nelson-liu** [comment]
awesome, thanks so much for the thorough response!

**Comment by YuffieHuang** [comment]
Hi!

I think I meet the same error:

```
  Traceback (most recent call last):
    File "run.py", line 628, in <module>
      main()
    File "run.py", line 461, in main
      if training_args.do_eval
    File "/Users/yfhuang/Documents/GitHub/LM-BFF/src/dataset.py", line 465, in __init__
      verbose=True if _ == 0 else False,
    File "/Users/yfhuang/Documents/GitHub/LM-BFF/src/dataset.py", line 585, in convert_fn
      other_sent_limit=self.args.other_sent_limit,
    File "/Users/yfhuang/Documents/GitHub/LM-BFF/src/dataset.py", line 244, in tokenize_multipart_input
      mask_pos = [input_ids.index(tokenizer.mask_token_id)]
  ValueError: 50264 is not in list
```

I was running the code on my own sentiment analysis dataset, which is similar to sst-5. The difference is that I only have 3 different labels instead of 5 classes compared to sst-5. Therefore, I modified "src/processors.py" and change the number of labels from 5 to 3. Then, I run the code on my own dataset with the task name "sst-5".

I'm not sure if it is a good way. The example for sst-5 works well, but my own test case cannot run properly. Can you please help me out? Thank you!
